# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Da5aqNzURI-8M-iIO8bx7RwawVpREke1
"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt
import numpy as np
from torch.utils.data import DataLoader

# ─────────────────────────────────────────────
# 0.  Device setup
# ─────────────────────────────────────────────
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")


# ─────────────────────────────────────────────
# 1.  PrunableLinear Layer
# ─────────────────────────────────────────────
class PrunableLinear(nn.Module):
    """
    A drop-in replacement for nn.Linear that includes a learnable gate
    for every weight.

    Forward pass:
        gates        = sigmoid(gate_scores)          ∈ (0, 1)
        pruned_w     = weight * gates                element-wise
        output       = x @ pruned_w.T + bias

    Because both `weight` and `gate_scores` are nn.Parameter objects,
    gradients flow through both automatically during backprop.
    """

    def __init__(self, in_features: int, out_features: int):
        super().__init__()
        self.in_features  = in_features
        self.out_features = out_features

        # Standard weight and bias (same init as nn.Linear)
        self.weight = nn.Parameter(torch.empty(out_features, in_features))
        self.bias   = nn.Parameter(torch.zeros(out_features))

        # Gate scores – same shape as weight; start near 0 so initial gates ≈ 0.5
        self.gate_scores = nn.Parameter(torch.zeros(out_features, in_features))

        # Kaiming uniform init for weight (good for ReLU networks)
        nn.init.kaiming_uniform_(self.weight, a=0.01)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        # Sigmoid squashes gate_scores → (0, 1)
        gates = torch.sigmoid(self.gate_scores)

        # Element-wise mask: weights with gate ≈ 0 are effectively removed
        pruned_weights = self.weight * gates

        # Standard linear transformation
        return torch.nn.functional.linear(x, pruned_weights, self.bias)

    def get_gates(self) -> torch.Tensor:
        """Return the current gate values (no gradient needed)."""
        with torch.no_grad():
            return torch.sigmoid(self.gate_scores)

    def extra_repr(self) -> str:
        return f"in_features={self.in_features}, out_features={self.out_features}"


# ─────────────────────────────────────────────
# 2.  Neural Network using PrunableLinear
# ─────────────────────────────────────────────
class PrunableNet(nn.Module):
    """
    Feed-forward network for CIFAR-10 (32×32×3 → 10 classes).
    All linear layers are replaced with PrunableLinear.
    """

    def __init__(self):
        super().__init__()
        # CIFAR-10 images are 32×32×3 = 3072 input features
        self.net = nn.Sequential(
            PrunableLinear(3072, 512),
            nn.BatchNorm1d(512),
            nn.ReLU(),
            nn.Dropout(0.3),

            PrunableLinear(512, 256),
            nn.BatchNorm1d(256),
            nn.ReLU(),
            nn.Dropout(0.3),

            PrunableLinear(256, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),

            PrunableLinear(128, 10),  # 10 CIFAR-10 classes
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = x.view(x.size(0), -1)   # flatten: (B, 3, 32, 32) → (B, 3072)
        return self.net(x)

    def get_all_gates(self) -> torch.Tensor:
        """Collect every gate value from every PrunableLinear layer."""
        gates = []
        for module in self.modules():
            if isinstance(module, PrunableLinear):
                gates.append(module.get_gates().view(-1))
        return torch.cat(gates)

    def sparsity_loss(self) -> torch.Tensor:
        """
        L1 penalty on all gate values.
        Since gates = sigmoid(·) ∈ (0,1), |gate| = gate, so this is
        simply the sum of all gate values across every PrunableLinear layer.
        """
        total = torch.tensor(0.0, device=device)
        for module in self.modules():
            if isinstance(module, PrunableLinear):
                gates = torch.sigmoid(module.gate_scores)
                total = total + gates.sum()
        return total


# ─────────────────────────────────────────────
# 3.  Data loading
# ─────────────────────────────────────────────
def get_dataloaders(batch_size: int = 128):
    """Download CIFAR-10 and return train / test DataLoaders."""
    train_transform = transforms.Compose([
        transforms.RandomHorizontalFlip(),
        transforms.RandomCrop(32, padding=4),
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465),
                             (0.2470, 0.2435, 0.2616)),
    ])
    test_transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465),
                             (0.2470, 0.2435, 0.2616)),
    ])

    train_set = torchvision.datasets.CIFAR10(
        root="./data", train=True,  download=True, transform=train_transform)
    test_set  = torchvision.datasets.CIFAR10(
        root="./data", train=False, download=True, transform=test_transform)

    train_loader = DataLoader(train_set, batch_size=batch_size,
                              shuffle=True,  num_workers=2, pin_memory=True)
    test_loader  = DataLoader(test_set,  batch_size=batch_size,
                              shuffle=False, num_workers=2, pin_memory=True)
    return train_loader, test_loader


# ─────────────────────────────────────────────
# 4.  Training loop
# ─────────────────────────────────────────────
def train(model: PrunableNet,
          train_loader: DataLoader,
          lam: float,
          num_epochs: int = 30,
          lr: float = 1e-3) -> list:
    """
    Train the model with:
        Total Loss = CrossEntropy(output, labels) + λ * L1(gates)

    Returns a list of (epoch, train_loss) tuples.
    """
    model.to(device)
    criterion = nn.CrossEntropyLoss()
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=1e-4)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=num_epochs)

    history = []
    for epoch in range(1, num_epochs + 1):
        model.train()
        total_loss_sum = 0.0
        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)

            optimizer.zero_grad()

            outputs  = model(images)
            ce_loss  = criterion(outputs, labels)
            sp_loss  = model.sparsity_loss()

            # ── The key equation ──────────────────────────────────
            total_loss = ce_loss + lam * sp_loss
            # ─────────────────────────────────────────────────────

            total_loss.backward()
            optimizer.step()
            total_loss_sum += total_loss.item()

        scheduler.step()
        avg_loss = total_loss_sum / len(train_loader)
        history.append((epoch, avg_loss))

        if epoch % 5 == 0 or epoch == 1:
            print(f"  Epoch {epoch:3d}/{num_epochs}  |  loss={avg_loss:.4f}"
                  f"  (λ={lam})")

    return history


# ─────────────────────────────────────────────
# 5.  Evaluation
# ─────────────────────────────────────────────
def evaluate(model: PrunableNet,
             test_loader: DataLoader,
             gate_threshold: float = 1e-2) -> tuple:
    """
    Returns:
        accuracy     – top-1 test accuracy (%)
        sparsity     – % of weights whose gate < threshold
    """
    model.eval()
    correct = total = 0
    with torch.no_grad():
        for images, labels in test_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            preds   = outputs.argmax(dim=1)
            correct += (preds == labels).sum().item()
            total   += labels.size(0)

    accuracy = 100.0 * correct / total

    # Sparsity: fraction of gates below threshold
    all_gates = model.get_all_gates().cpu().numpy()
    sparsity  = 100.0 * (all_gates < gate_threshold).mean()

    return accuracy, sparsity, all_gates


# ─────────────────────────────────────────────
# 6.  Main experiment: sweep over λ values
# ─────────────────────────────────────────────
def main():
    LAMBDAS    = [1e-5, 1e-4, 1e-3]  # low, medium, high
    NUM_EPOCHS = 30
    BATCH_SIZE = 128

    print("Downloading / loading CIFAR-10 …")
    train_loader, test_loader = get_dataloaders(BATCH_SIZE)

    results   = []   # (lam, accuracy, sparsity)
    all_gates_per_lam = {}

    for lam in LAMBDAS:
        print(f"\n{'='*55}")
        print(f"  Training with λ = {lam}")
        print(f"{'='*55}")

        model = PrunableNet()
        train(model, train_loader, lam=lam, num_epochs=NUM_EPOCHS)

        accuracy, sparsity, gates = evaluate(model, test_loader)
        results.append((lam, accuracy, sparsity))
        all_gates_per_lam[lam] = gates

        print(f"\n  ► Test accuracy : {accuracy:.2f}%")
        print(f"  ► Sparsity      : {sparsity:.2f}% of gates < 1e-2")

    # ── Print results table ──────────────────────────────────────
    print(f"\n\n{'='*50}")
    print(f"  {'Lambda':<12} {'Test Accuracy':>14} {'Sparsity (%)':>14}")
    print(f"  {'-'*40}")
    for lam, acc, sp in results:
        print(f"  {lam:<12} {acc:>13.2f}% {sp:>13.2f}%")
    print(f"{'='*50}\n")

    # ── Gate distribution plot ───────────────────────────────────
    fig, axes = plt.subplots(1, 3, figsize=(15, 4), sharey=False)
    fig.suptitle("Gate Value Distribution for Different λ", fontsize=14, fontweight="bold")

    for ax, (lam, acc, sp) in zip(axes, results):
        gates = all_gates_per_lam[lam]
        ax.hist(gates, bins=80, color="steelblue", edgecolor="white", linewidth=0.3)
        ax.set_title(f"λ = {lam}\nAcc={acc:.1f}%  Sparse={sp:.1f}%", fontsize=10)
        ax.set_xlabel("Gate value (sigmoid output)")
        ax.set_ylabel("Count")
        ax.axvline(x=0.01, color="red", linestyle="--", linewidth=1, label="threshold=0.01")
        ax.legend(fontsize=8)

    plt.tight_layout()
    plt.savefig("gate_distribution.png", dpi=150, bbox_inches="tight")
    print("Gate distribution plot saved → gate_distribution.png")
    plt.show()


if __name__ == "__main__":
    main()